### ISSUE TITLE
Figure out how to make JSON versions of the portal pages

### ISSUE THREAD

**Issue by raquel-ucl** [oracc/website#15] opened 2017-12-14 13:59 UTC

**Comment by stinney** [comment] 2018-01-10 02:29
This is done. It's not documented yet but it's very simple so that should be an issue.  Oracc portal pages produced by its ESP2 portal subsystem now put an ID on every block content node.  These are turned into JSON chunks with a URL that uses the ID in the hashref.

Each project creates its own PROJECTNAME-portal.json, where subprojects have / mapped to - in the project name, so: amgg-portal.json but cams-gkab-portal.json. Most projects have not been rebuilt since the portal-json generation was introduced--this will happen over time and can be forced later to build a complete set of JSON portal pages when we need them.  Enough is available now for meaningful implementation and testing.

The uber-project, NEO, collects all of the XXX-portal.json files together in a directory portalpages and then adds them to its zipfile including the directory.

As of about 9:30pm EST on 2018-01-09, NEO is still building.  I'll check that it has built correctly and close this issue when I've confirmed that the portalpages directory is properly included in http://build-oracc.museum.upenn.edu/json/neo.zip .

**Comment by stinney** [comment] 2018-01-10 02:32
*should NOT be an issue :)

**Comment by stinney** [comment] 2018-01-10 04:09
OK the zip looks good; closing this issue now.

**Closed by stinney** 2018-01-10 04:09 UTC
